# .github/workflows/dependabot2jira.yml
name: Dependabo jira ticket

permissions: {}

on:
  pull_request:
    types: [opened]

jobs:
  run-if-grom72:
    if: github.actor == 'grom72'
    runs-on: ubuntu-latest
    steps:
      - name: Send request to Jira
        env:
          TITLE: ${{ github.event.pull_request.title }}
          BODY: ${{ github.event.pull_request.title }}
        run: |
          jira_response=$(curl -u "${{ secrets.JIRA_USERNAME }}:${{ secrets.JIRA_PASSWORD }}" \
            --verbose \
            -X POST \
            -H "Content-Type: application/json" \
            --data "$(jq -n --arg title "$TITLE" \
                           --arg body "$BODY" \
                           '{
                              fields: {
                                project: { key: "PMDK" },
                                summary: $title,
                                description: $body,
                                issuetype: { name: "Bug" }
                              }
                            }')" "https://daosio.atlassian.net/rest/api/2/issue")
          ticket_key=$(echo "$jira_response" | jq -r .key)
          new_title="$ticket_key cq: $TITLE"
          echo $new_title
