name: Trivy checking

on:
  workflow_dispatch:
  schedule:
    # run this job at 23:00 UTC every other day
    - cron: '0 23 */2 * *'
  push:
    branches:
      - master
      - 'feature/*'
      - 'release/*'
  pull_request:


jobs:
  upgrade-check:
    name: Trivy checking
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install trivy package
        run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | \
          sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy

      - name: Generate trivy report
        run: |
          trivy fs -c ci/trivy/trivy.yaml \
           --output trivy-report-daos.$(git branch --show-current | sed -e 's/release\///').csv .

      - uses: actions/upload-artifact@v4
        with:
          path: trivy-report-daos.*

      - name: Scan with trivy
        run: trivy fs -c ci/trivy/trivy.yaml --exit-code 1 .
